from distutils.core import setup setup(
  name = 'dexonline',         
  packages = ['dexonline'],   
  version = '0.1',
  license='MIT',
  description = 'API neoficial pentru https://dexonline.ro',
  author = 'Nandra Rares',
  author_email = 'nandrarares16@gmail.com',
  url = 'https://github.com/Dexter0-0/dexonline-API/tree/master',
  download_url = '!ADD!',
  keywords = ['dexonline', 'dex', 'dictionar', 'sinonime', 'antonime', 'rime', 'prefixe', 'sufixe', 'cuvant', "cuvinte"],
  install_requires=['lxml', 'requests', "unidecode", "datetime"],
  classifiers=[
    'Development Status :: 3 - Alpha',   
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
  ],
)
